### ISSUE TITLE
Update httpx dependency

### ISSUE THREAD

**Issue by abiodunjames** [marcosschroh/python-schema-registry-client#111]
In my project, I used one of the recent versions of `httpx` and `pytest-httpx`. To use this package, I have to downgrade the httpx dependencies to a much lower version because the python-schema-registry client uses `httpx>=0.14,<0.15`.   Could we update or upgrade this?

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/114
