### ISSUE TITLE
How to login in scheme-registry-client, using api-key and secrete

### ISSUE THREAD

**Issue by desharma12** [marcosschroh/python-schema-registry-client#123]
Hi,
I am using "python-schema-registry-client==2.2.2", I want to login in schema registry client, using "api-key" and "secrete", it is using basic-auth, like:

`client = SchemaRegistryClient(url='scheme-registry-example.com', api-key='xxxx', password='xxxx')` but this example is not working

there is some tutorial  for   "ca_location, cert_location, key_location", but i don't want to use ca.location

Please suggest, how to pass "api-key" and "password" for basic auth to access it.

Thanks

**Comment by NicoRLasso** [comment]
Hi @desharma12 did you solve this issue? because i have the same one

**Comment by marcosschroh** [comment]
Hi, 

Sorry for the delay. Can you try to pass the url as a `dict` like:

```python
{
    "url": "your-url",
    "basic.auth.credentials.source": "USER_INFO",
    "basic.auth.user.info": "api-key:password",
}
```

If this doesn’t work I will try to take a look asap.

**Comment by NicoRLasso** [comment]
Hi @marcosschroh  yes I did it like that and forgot to post the answer thanks !!!

**Comment by marcosschroh** [comment]
Cool, good to know that it worked. I will improve the documentation with this. Thanks

**Comment by marcosschroh** [comment]
I have added a new [Auth](https://marcosschroh.github.io/python-schema-registry-client/client/#auth) parameter to make it easier to provide `username` and `password`. 

Closed by https://github.com/marcosschroh/python-schema-registry-client/pull/127.
