### ISSUE TITLE
Support for multiple schema registry base urls

### ISSUE THREAD

**Issue by HuM4NoiD** [marcosschroh/python-schema-registry-client#140]
Is it possible to provide multiple schema registry base urls in the `url` parameter of `AsyncSchemaRegistryClient`?
something like:
```python
client = AsyncSchemaRegistryClient(url="http://host1:port1,http://user:pass@host2:port2")
```

This is for the case when one of the hosts is unresponsive.

**Comment by marcosschroh** [comment]
Hi @HuM4NoiD 

We do not have support for this as underlying we are using `httpx` and it is not possible to provide more than one `url`. Anyway, think you should always have one url and behind it you could have multiple `schema servers` running in a [Multi-Datacenter Setup](https://docs.confluent.io/platform/current/schema-registry/multidc.html#schemaregistry-mirroring) then you will have one endpoint and if for any reason the schema server leader fails then a slave/secondary server will continue serving the requests. 

You can find more info [here](https://docs.confluent.io/platform/current/schema-registry/multidc.html#id4)
