### ISSUE TITLE
Support httpx.Auth in SchemaRegistryClient

### ISSUE THREAD

**Issue by cbcoutinho** [marcosschroh/python-schema-registry-client#173]
**Is your feature request related to a problem? Please describe.**

Schema registries hosted by some cloud providers (e.g. [Confluent](https://docs.confluent.io/cloud/current/access-management/authenticate/oauth/configure-clients-oauth.html#configure-sr-clients-for-oauth), [Azure Event Hubs](https://learn.microsoft.com/en-us/azure/event-hubs/authenticate-application)) support OAuth2 bearer token authorization in addition to basic user auth. This simplifies a number of governance challenges related to credential management, and allows teams to build off of existing RBAC assignments.

**Describe the solution you'd like**

Enable a way to utilize a token provider when initializing the `SchemaRegistryClient`, such that all requests can be authorized using a dynamic bearer token. Refreshing the token can be left as a responsibility to the token provider interface.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/174
