### ISSUE TITLE
Schema version not always in schema

### ISSUE THREAD

**Issue by alex3165** [marcosschroh/python-schema-registry-client#29]
**Describe the bug**
https://github.com/marcosschroh/python-schema-registry-client/blob/master/schema_registry/client/client.py#L340 assume version is a property in schema

**To Reproduce**
```
from schema_registry.client import SchemaRegistryClient, schema
from schema_registry.serializers import FaustSerializer
from faust.serializers import codecs


client = SchemaRegistryClient(
    url='SCHEMA_REGISTRY_URL')

schema = client.get_schema('TEST_OUTPUT_TOPIC-value')

avro_metadata_schema = schema.AvroSchema(schema.schema)
```
Running this throw an error:
```
CRASHING HARD: COORDINATION ROUTINE GOT AttributeError("'SchemaVersion' object has no attribute 'AvroSchema'",)
```

I think this is because there is no `version` property in my schema and the library assume there should be

**Comment by marcosschroh** [comment]
hi, thank you for reporting it! I will take a look.

**Comment by marcosschroh** [comment]
Hi @alex3165,

I am taking a look the code snippet that you wrote above, and I think you are overriding the `schema` module with tha `schema` variable.

```python
# here when you import
from schema_registry.client import SchemaRegistryClient, schema
...

# overriding
schema = client.get_schema('TEST_OUTPUT_TOPIC-value')

# so, now schema is `SchemaVersion` type and does noot have the attribute `AvroSchema`
```

Sorry, for the confusion. Can you check this please?

Maybe we should rename the module `schema` to `schemas`.

**Comment by marcosschroh** [comment]
Any updates @alex3165 ?

**Comment by marcosschroh** [comment]
Is not a bug in the library. In the example given  `schema` is `SchemaVersion` and only have 4 attributes: `subject`, `schema_id`, `schema` and `version`. 

The module `schema_registry.client.schema` could be renamed to `schema_registry.client.schemas` to avoid confusion.
