### ISSUE TITLE
Support of Faust 1.9.0

### ISSUE THREAD

**Issue by krejcmat** [marcosschroh/python-schema-registry-client#33]
The latest version of **python-schema-registry-client** supports faust<=1.8.1. Would be great to support Faust 1.9.0 since there are crucial bugfixes.

**Comment by marcosschroh** [comment]
Hi @krejcmat 

Yes, I agree. I will update the library to use the latest version of `faust`.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/34
