### ISSUE TITLE
Support AsyncIO, with aiohttp

### ISSUE THREAD

**Issue by matrixise** [marcosschroh/python-schema-registry-client#35]
Currently, if we want to use your library with asyncio, we need to execute it with loop.run_in_executor, and that solution will use a ThreadPoolExecutor, not really interesting.

Please, could you consider to add an asynchronous part with the aiohttp's client?

Thank you.

**Comment by marcosschroh** [comment]
Hi @matrixise 

I have created another project to work with `asyncio` that uses `requests-async`: https://github.com/marcosschroh/async-python-schema-registry-client
