### ISSUE TITLE
Add a flag to suppress the fastavro parsed maker. 

### ISSUE THREAD

**Issue by martinpmsmith** [marcosschroh/python-schema-registry-client#52]
First off great API it solves and issue I was having.  However I don't see a flag to turn off the generation of    , "__fastavro_parsed": True  .  This causes an issue if I try to pass the schema to an Avro serializer or deserializer.  I have a work around by simply removing text. 

**Describe the solution you'd like**
I would like to see a Boolean on the get_schema call that gets passed to the fastavro  parse schema method's.  write_hint parameter. 

_write_hint (bool) – Internal API argument specifying whether or not the __fastavro_parsed marker should be added to the schema

**Comment by marcosschroh** [comment]
Hi @martinpmsmith ,

Thanks for reporting the issue. Maybe we could:

1. Add an extra method to the class `schema_registry.client.schema.AvroSchema` so you can get the parsed schema with/without the flag `__fastavro_parsed`?
2. Store the schema parsed without `__fastavro_parsed` directly. 

So, with this any method that returns schema will have the same behaviour. 

what do you think?

**Comment by martinpmsmith** [comment]
Hi, 

I was actually thinking an additional optional named parameter to the existing get_shema method set to True .   This way any existing code still works. 


def get_schema(subject: str, version="latest", headers: dict = None, include_fastavro: bool = True) -> utils.SchemaVersion:
    """


Martin

**Comment by marcosschroh** [comment]
Your solution will work, but it means that you need to include the functionality in the `get_schema` function to remove the `__fastavro_parsed`. If you go for option 2, existing code will work as before and also people could use a the new property of `schema_registry.client.schema.AvroSchema`. Maybe better with the example code:

```python
class AvroSchema:
    def __init__(self, schema: str) -> None:
        if isinstance(schema, str):
            schema = json.loads(schema)
        self.schema = fastavro.parse_schema(schema, _force=True)
     ...
      
    @property
    def clean_schema(self):
        # remove `__fastavro_parsed` field fro dict
        ...
        return cleaned_schema
```

Then, in your code you will use the `clean_schema` method.

```python
client = Client()

schema_version = client.get_schema(....)

schema_version.schema.clean_payload
```

Also, this new functionality will be available for all methods that return a `AvroSchema` or `SchemaVersion`, for example: `get_by_id`, `check_version` and in this case `get_schema`
 
what do you think?

**Comment by martinpmsmith** [comment]
Ok I get your thinking and prefer your approach. 

Martin

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/53

Now you can do:
```python
client = Client()

schema_version = client.get_schema(....)

schema_version.schema.flat_schema
```

**Comment by martinpmsmith** [comment]
Noticed a typo on the documentation page https://marcosschroh.github.io/python-schema-registry-client/schemas/ <https://marcosschroh.github.io/python-schema-registry-client/schemas/>    flat schema has an n. Instead of an m.   

Martin

**Comment by marcosschroh** [comment]
Thanks! Fixed
