### ISSUE TITLE
Set timeout to schema-registry requests

### ISSUE THREAD

**Issue by vansimonsen** [marcosschroh/python-schema-registry-client#54]
**Is your feature request related to a problem? Please describe.**
We can't specify a request time when we need to get or encode an schema

**Describe the solution you'd like**
Set from outside a timeout value to pass to internal request

**Comment by marcosschroh** [comment]
Hi @vansimonsen 

Ok. A few question to know the context: Are you having some issues with the Schema Registry Server and the response takes a lot of time? Are you using Faust?

**Comment by vansimonsen** [comment]
Hi!
I have few Connection Errors trying to encode data with `schema_id` (less than 1%, at least).
I want to create different retry strategies, but I'd like have some control on how much every request could wait until Timeout. (If my strategy is well planned)
Related to faust, nop, I'm not using it.

Thanks in advance!

**Comment by marcosschroh** [comment]
Thanks. I will work on this feature.

**Comment by marcosschroh** [comment]
Hi @vansimonsen , 

I have created a [PR](https://github.com/marcosschroh/python-schema-registry-client/pull/57). You can take a look. With this changes will be possible to set the `timeout` when the `SchemaRegistryClient` is instantiated or per method.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/57. Released in version `1.4.0`

**Comment by vansimonsen** [comment]
Thanks a lot!
Sorry by absence

It's great to have this setting available, I reviewed and everything looks good.
Thanks again
