### ISSUE TITLE
SchemaRegistryClient fails to instantiate due to httpx changes

### ISSUE THREAD

**Issue by mgorsk1** [marcosschroh/python-schema-registry-client#67]
**Describe the bug**

Failure to instantiate client:

```
File "/usr/local/lib/python3.7/site-packages/schema_registry/client/client.py", line 45, in SchemaRegistryClient
--
  | pool_limits: httpx.PoolLimits = httpx._config.DEFAULT_POOL_LIMITS,
  | AttributeError: module 'httpx._config' has no attribute 'DEFAULT_POOL_LIMITS'
```

It's most likely caused by changes in httpx library (particular version is not pinned in schema registry client deps)

https://github.com/encode/httpx/commit/f67e925f72166ac89c4ff430540173b5910ec315#diff-11c528b34fa1b897a86107c0a46b252f

Explicit downgrade httpx to 0.13.3 resolves this issue.

**To Reproduce**

Install python schema registry client with latest httpx lib and try to create client.

**Expected behavior**
Client is created ok.

**Comment by marcosschroh** [comment]
Hi @mgorsk1 

That is weird because this issue was fixed by @com4 in https://github.com/marcosschroh/python-schema-registry-client/pull/66

**Comment by miandreu** [comment]
Same issue here @marcosschroh today, in our case we are using the 1.4.2 version but this shouldn't make any change

**Comment by marcosschroh** [comment]
Yes, the version `1.4.2` has the fix for the new `httpx` release. Thanks @miandreu

**Comment by com4** [comment]
@mgorsk1 As Marcos points out, version 1.4.2 should fix your issue (i.e. https://github.com/marcosschroh/python-schema-registry-client/blob/master/schema_registry/client/client.py#L45 no longer references `httpx._config.DEFAULT_POOL_LIMITS`).

@miandreu The full traceback of your error and the output of  `python -mpip list | grep "python-schema-registry-client\|httpx"` might help narrow down where exactly you're seeing this issue.

**Comment by mgorsk1** [comment]
Thanks, indeed version bump was enough. Sorry for the bother !
