### ISSUE TITLE
Missing Argument is_key

### ISSUE THREAD

**Issue by Reapor-Yurnero** [marcosschroh/python-schema-registry-client#74]
**Describe the bug**
In message_serializer.py,  both `encode_record_with_schema` and `encode_record_with_schema_id` claim to have the `is_key` argument in the docstring, however the function definition does not have `is_key` at all. I guess this is a missing implementation?
**To Reproduce**
N.A.

**Expected behavior**
N.A.

**Comment by Reapor-Yurnero** [comment]
I think this is a problem existing for a long time. Surprised it's not discovered or solved and nobody is reacting to this issue though this repo is actively updated.

**Comment by marcosschroh** [comment]
Hi @Reapor-Yurnero 

Sorry for the delay. I will take a look into it!

**Comment by marcosschroh** [comment]
@Reapor-Yurnero I have check the issue and the `docstrings` of both methods must be updated. The `is_key` should be removed. Also, the `doc` must be updated.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/76

**Comment by Reapor-Yurnero** [comment]
I'm glad to hear that. Thanks!
