### ISSUE TITLE
Fastavro-parsed schema registered at schema registry

### ISSUE THREAD

**Issue by forsberg** [marcosschroh/python-schema-registry-client#77]
**Describe the bug**
The library registers the schema after it has been parsed by fastavro, which will reformat the schema and add extra metadata.

**To Reproduce**
1. Register a schema using the library.
2. Inspect the schema in the schema registry.

**Expected behavior**
Exact same schema that was sent as argument to library was registered in schema registry.

If this is expected behaviour, an explanation on why would be appreciated. It is clearly confusing for the developer, adds extra information to the registry which is not useful for non-fastavro based schema registry clients, and also caused me troulbe in a way I could not work around as long as python-schema-registry-client has this behaviour - see 
https://github.com/Apicurio/apicurio-registry/issues/300#issuecomment-682495770

**Comment by marcosschroh** [comment]
Thanks @forsberg. Make sense
