### ISSUE TITLE
No Async Message Serializer

### ISSUE THREAD

**Issue by jsonbrooks** [marcosschroh/python-schema-registry-client#90]
I can see a message serializer that uses the syncronous client, but not one that uses the async version.

**Comment by marcosschroh** [comment]
you are correct @jsonbrooks . Would you like to send a `PR` and add it? we can discuss possible solutions and you can implement it. What do you think?

**Comment by jsonbrooks** [comment]
I slapped together the following for my own purposes. It doesn't quite do everything yours does, as it's only exactly what I need, but feel free to copy it or some variation in:

`
class KafkaAvroSerializer:

    def __init__(self, schema_registry_host: str = 'localhost', schema_registry_port: int = 8081):
        self.reg_client = AsyncSchemaRegistryClient(url=f'{schema_registry_host}:{schema_registry_port}')

    async def register_schemas(self, schemas_by_subject: Dict[str, Dict]):
        """
        Registers all given schemas with schema registry. This step is required for serialization.
        schemas arg is dictionary with subjects as keys and avro schemas as values.
        """
        await asyncio.gather(
            [self.reg_client.register(subject, AvroSchema(schema))
             for subject, schema in schemas_by_subject]
        )

    def serialize(self, subject: str, data: Any) -> bytes:
        """
        Serialize message in avro format. Writes avro without schema in header. Instead, writes schema_id
        first according to kafka wire format.
        """
        buf = BytesIO()
        schema_id = self.reg_client.subject_to_schema_ids[subject]
        parsed_fastavro_schema = self.reg_client.id_to_schema[schema_id].schema
        buf.write(struct.pack(">bI", 0, schema_id))
        schemaless_writer(buf, parsed_fastavro_schema, data)
        return buf.read()
`

**Comment by marcosschroh** [comment]
Hi @jsonbrooks 

Thanks for the proposal. I think that the new serializer (`AsyncSerializer`) should respect the same interface of the `MessageSerializer`, for example `register_schemas` should not be part of the new Serializer. Register schemas is a client responsibility. What I would like to have here is an `AsyncSerializer`, that does exactely the same as the `MessageSerializer` but `async`, having a base class, so we can share the common behaviour (which should be most of the code. What a like is the way of redefining the methods `decode_message` and `decode_message` to `serialize` and `deserialize` respectively.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/102
