### ISSUE TITLE
AvroSchema init has invalid arg type

### ISSUE THREAD

**Issue by jsonbrooks** [marcosschroh/python-schema-registry-client#92]
Your AvroSchema class has an incorrect type on the "schema" arg. PyCharm complains about it.

```
class AvroSchema:
    def __init__(self, schema: str) -> None:
```

should be:
```
class AvroSchema:
    def __init__(self, schema: Union[str, Dict]) -> None:
```

**Comment by marcosschroh** [comment]
Thanks. You can send a PR with the fix. `mypy` will check it

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/95
