### ISSUE TITLE
AsyncSchemaRegistryClient.register logs ERROR in normal operation

### ISSUE THREAD

**Issue by jsonbrooks** [marcosschroh/python-schema-registry-client#93]
When I call `AsyncSchemaRegistryClient.register` with a schema that's not registered yet, it logs with an "ERROR" level that it doesn't exist yet. This does not seem appropriate to me, since it's normal, expected operation. Can you change this to "INFO"

`ERROR    schema_registry.client.client:client.py:1011 Not found: 404`

**Comment by marcosschroh** [comment]
Hi @jsonbrooks , you are completely correct. Do you want to send a PR with the fix?

**Comment by PJ-Schulz** [comment]
I get the same error when I get the Avro schema from the registry and do the first dump with FaustSerializer.
On the first call, the serializer printed `Not found 404` , but not on the following ones. 

Although the error is printed the at the first time, the message is serialised anyway.


```
from schema_registry.client import SchemaRegistryClient, schema
from schema_registry.serializers import FaustSerializer

client = SchemaRegistryClient(...)

registered_schema = client.get_schema(subject='xxx')
avro_serializer = FaustSerializer(client, 'xxx', schema.AvroSchema(registered_schema.schema.schema))
for measurement in measurements:
    avro_serializer.dumps(measurement)
```

How can I avoid the Error message?

**Comment by marcosschroh** [comment]
@PJ-Schulz The error id because first we check whether the schema already exists. The error is related with a `404` (not found), so because the schema is was not registered, we do it. I will change the log level to `info`.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/94
